pipeline {
    agent any

    environment{
        def devserver = "35.223.184.244"
    }

    parameters{
        string(defaultValue:"DEV", description: "Which environment to deploy?", name: "deployEnv")
    }
       
    stages {
        stage('Install requirements on server') {
            steps {
                echo 'Install requirements on ${deployEnv} server'
                sh 'pwd'                              
                sshPublisher(publishers: [sshPublisherDesc(configName: 'appserver', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: 'pip install -r requirements.txt', execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '', remoteDirectorySDF: false, removePrefix: '', sourceFiles: 'requirements.txt')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
            }
        }       
        stage('Start Flask WebApp on DEV server') {
            steps {
                echo 'Start Flask WebApp on DEV server'
                sh 'pwd'
                sh "ssh jenkins@35.233.184.244 'timeout 10s nohup python3 app.py &'"                
            }
        }
        stage('Test on DEV server') {
            steps {
                echo 'Test on DEV server'
                sh 'pwd'
                sshPublisher(publishers: [sshPublisherDesc(configName: 'appserver', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: 'python3 test.py', execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '', remoteDirectorySDF: false, removePrefix: '', sourceFiles: 'test.py')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
            }
            post {
                always {
                    junit 'test-reports/*.xml'
                }
            }
        }
       
    }
}
